# Centralized config for search-service

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/connectsphere_search?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true